### ISSUE TITLE
（login.py约36行处）pwd_default_encrypt_salt正则表达式似乎找不到了

### ISSUE THREAD

**Issue by ZhengQinLai** [billchenchina/hitutil#5]
大概是统一认证网页有了一点改动
把soup提前，并更换为：
    soup = BeautifulSoup(r1.text, 'html.parser')
    pwd_default_encrypt_salt = soup.find('input', {'id': 'pwdEncryptSalt'})['value']
应该就好使了
还有就是检测是否登陆成功的地方，应该更换一个对比地址
大佬可以 测试一下...不知道我改的有没有问题

**Comment by billchenchina** [comment]
#4

**Comment by ZhengQinLai** [comment]
啊 我没看到...不好意思
